### PR TITLE
Korean Translation of 'Working and Saving are Revolutionary Acts'

### PR DESCRIPTION
**Pull request by sogoagain**
Hello,

I've translated 'Working and Saving are Revolutionary Acts' into Korean.
I plan to continue contributing translations.

Thanks for the great resources on your site.

### CODE REVIEW

**Comment by bitstein** [comment]
Thank you so much! I look forward to more translations. Please keep in touch.

**Comment by bitstein** [comment]
@sogoagain It is now live here: https://nakamotoinstitute.org/mempool/working-and-saving-are-revolutionary-acts/ko/

**Comment by sogoagain** [comment]
@bitstein 

I'm thrilled to see my translation live and contributing to the community!

However, I noticed some formatting discrepancies due to VSCode's auto-format feature, which altered the markdown from the original text. To rectify this, I've submitted a new PR with the corrections.
(https://github.com/NakamotoInstitute/nakamotoinstitute.org/pull/263)

I'm excited to continue learning from the content and contributing more translations in the future.
Thank you.

**Comment by bitstein** [comment]
Thank you for that. This current implementation of the website uses an old markdown renderer that does not play nicely with how Prettier formats markdown. I'm working on overhauls that include using Commonmark standards that will fix this.

**Pull request merged**
