### PR TITLE
Who controls Bitcoin in Russian

### PR DESCRIPTION
**Pull request by engenegr**
Let me introduce russian translation in *.md.
I've tried to make it very close to the original text.

### CODE REVIEW

**Comment by vikbtc** [comment]
The original article refers to a BitcoinTalk thread ("This thread on BitcoinTalk argues..."), but there is no link.  @DanielKrawisz any idea what the missing link is?

**Comment by vikbtc** [comment]
I'm OK with this translation. The only issue is it's missing the link to the BitcoinTalk thread, which is missing in the original en version (see above comment). We also need to add the translation links to blogposts.json and the en version.

**Comment by engenegr** [comment]
Hey all, the second article is pulled. 
"I’m Hoarding Bitcoins, and No You Can’t Have Any"
I've tried to copy-paste images like in other posts. It needs to be checked, probably.

**Comment by bitstein** [comment]
Thank you, @engenegr! I'm going to add the extra links and such the pages need today. I'll push this this branch. When @vikbtc gives the thumbs up on this other translation, I'll merge and deploy both.

This is awesome.

**Comment by vikbtc** [comment]
@bitstein I've reviewed this, you can go ahead and merge.

**Pull request merged**
