### PR TITLE
Immortalize early front runners

### PR DESCRIPTION
**Pull request by kngako**

### CODE REVIEW

**Comment by PierreRochard** [comment]
Concept ACK

**Comment by bitstein** [comment]
Concept ACK.

I love the idea. I think a good editorial policy on this would be that they need to be a public figure. I love the Bitcoin plebs, but this page would need infinite scroll for all the good Bitcoiner calls. We should confine this to exogenous entrance into Bitcoin (plus Satoshi).

**Comment by bitstein** [comment]
I think it would be good to shorten "The Front Running Of The Bulls" to "The Front-Runners", to mirror "The Skeptics." We can also put a YouTube embed in the header for [_The Run of the Golden Bull_](https://www.youtube.com/watch?v=nJeddv1QbeQ).

**Comment by kngako** [comment]
The video looks dope on the page. Feel free to edit the `data/front_runners.json` set with better entries.

**Comment by PierreRochard** [comment]
I actually like the idea of infinite scroll, plebs and gigachads sharing in the glory of understanding

**Comment by bitstein** [comment]
Fair! The question is what constitutes a strong enough statement to earn a place on this? Notable people have it easier, because they can just say something bullish in the news, or make a large purchase. I'm not sure what the minimum criteria would be for plebs.

I'd also like to have it like the Skeptics where it captures the _earliest_ bold statement from someone, not every single one (imagine having to scroll through that much Schiff and Roubini...).

**Comment by kngako** [comment]
> The question is what constitutes a strong enough statement to earn a place on this?

With the few entries I had I was considering the **novelty of the statement/action/circumstance at the time at was made** as a heuristic for entries?

By this heuristic Hal Finney's price prediction of $10 Million per coin on January 2009 kinda sets the bar way high for most other price predictions and minimizes the number of price predictions that could become entries (unless they are culture quotables)?  

Then there are other novel actions like the Bitcoin pizza day which was among the first events that helped facilitate price discovery. Could have some room for such events too?

**Comment by bitstein** [comment]
I am closing this for now, as it is not a high priority at the moment.

**Pull request closed without merging**
